// Copyright (c) 2018 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-layout: guide-multipane
:projectid: template
:page-duration: 15 minutes
:page-releasedate: 2018-05-14
:page-description: Learn how to create a todo list API as a REST service using JAX-RS, and Open Liberty.
:page-tags: ['MicroProfile', 'Maven', 'Java EE', 'Gradle']
:page-related-guides: ['cdi-intro', 'rest-intro']
:page-guide-category: microprofile
:page-essential: false
:page-essential-order: 3
:page-permalink: /guides/{projectid}
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
:page-seo-title: Creating a REST service
:page-seo-description: Find out how to create a REST service on Open Liberty
:guide-author: Open Liberty

= Title of guide, starting with a gerund (Creating, Administering, and so on)
// EXAMPLE: Creating a REST API for a todo list application

[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form, view it on the https://openliberty.io/guides/{projectid}.html[Open Liberty website].

// Start the introduction with "You'll explore how to..." or something similarly catchy.
// Write no more than two sentences, with meaningful information on what the user can accomplish
// with this guide.
// Do not start the introduction with "This guide...".
// EXAMPLE: Learn how to create a todo list API as a REST service using JAX-RS, CDI, and Open Liberty.

== What you'll learn

// Delete the following notes as you write your guide
//-----------------------------------------------------

This guide is a sample guide to help you get started with writing your own. 
This document is the README.adoc where you will be writing your guide. 
See https://github.com/OpenLiberty/draft-guides-template/wiki/README-breakdown[README breakdown] to understand how to fill out the front matter and specific instructions on the syntax of writing your guide.
Before you get started you will want to follow these steps: https://github.com/OpenLiberty/draft-guides-template/wiki/Instructions-to-start-writing-a-guide[Instructions to start writing your own guide]
The what you'll learn section is where you will be writing about what the user will learn in a meaningful introduction paragraph. Follow the introduction paragraph with more details of what the user will learn, but still keep it brief. See the https://openliberty.io/guides/rest-intro.html[REST guide] at as an exemplar guide.

//-----------------------------------------------------


== Getting started

// Delete the following notes as you write your guide
//-----------------------------------------------------

Add this getting started section to your guide if it is applicable. 
Use the following include to pull in the git clone instructions from the guides-common repository.

//-----------------------------------------------------


[role="command"]
include::{common-includes}/gitclone.adoc[]




=== Try what you’ll build

// Delete the following notes as you write your guide
//-----------------------------------------------------

This is a subsection of the "Getting Started" section above. It should briefly walk the user through how to setup everything in the "finish"
directory and try out the finished version of what they will be building.
Use the following include that explains what the finish directory and asks the users to run `mvn install` and `mvn liberty:start-server` in the finish directory.
If this applies to your guide, keep the trywhatyoubuild-intro.adoc[] include.

//-----------------------------------------------------


[role="command"]
 include::{common-includes}/trywhatyoubuild-intro.adoc[]

// Delete the following notes as you write your guide
//-----------------------------------------------------

Here, you will include a brief explanation on how to use the finished application. 
Describe what the user expects to see after running the completed version of the application.
Use the following include that asks users to stop the liberty server with `mvn liberty:stop-server` if they started a server previously.
If this applies to your guide, keep the trywhatyoubuild-end.adoc[] include.

//-----------------------------------------------------

[role="command"]
include::{common-includes}/trywhatyoubuild-end.adoc[]


== Section title for this section, starting with a gerund like Creating, Building, etc

// Delete the following notes as you write your guide
//-----------------------------------------------------

Add the various sections that are needed for your particular guide.
Start each additional section title with a meaningful gerund such as Creating, Building, Testing.
Follow the gerund with a meaningful noun phrase. For example: Creating a JAX-RS application
Examples: 
* Learning to use JAX-RS and CDI
* Learning how to build a REST service for a todo list application

Write a sentence with the context like "Navigate to the `start` directory to begin." in the section where user starts working with the implementation.

What to add for each section:
* Start each section with a meaningful description about what the user is doing in the section.
* Include code snippets.
* Avoid making all the documentation a series of steps and tasks, bullets, or numbered lists.
* Use tick marks around directories, files, values, class names, method names, and so on.
* Use hotspots to highlight files in the right pane as described in 
* Example: `this-is-a-file`, `this/is/a/path`, `thisIsAMethod`.

//-----------------------------------------------------



// EXAMPLE: The following block demostrates how different sections look like for a todo application.
// ======================================================================================================
== Building the model

Navigate to the `start` directory. You will represent an entry in a todo list.

[role="code_command", subs="quotes"]
----
#Create the `TodoModel` class.#
`src/main/java/io/openliberty/guides/todolistSample/models/TodoModel.java`
----

TodoModel.java
[source, Java, linenums, role='code_column']
----
link:finish/src/main/java/io/openliberty/guides/todolistSample/models/TodoModel.java[]
----

The [hotspot]`ToDoModel` has three getters: [hotspot=26-28]`getTitle()`, [hotspot=30-32]`getCompleted()` 
and [hotspot=34-36]`getId()` and three setters: [hotspot=42-44]`setTitle()`, [hotspot=46-48]`setCompleted()` and [hotspot=50-52]`setId()`.


== Creating the Manager

Next, we will create a manager that is injected into the JAX-RS resource.


[role="code_command", subs="quotes"]
----
#Create the `TodoManager` class.#
`src/main/java/io/openliberty/guides/todolistSample/managers/TodoManager.java`
----

TodoManager.java
[source, Java, linenums, role='code_column']
----
link:finish/src/main/java/io/openliberty/guides/todolistSample/managers/TodoManagers.java[]
----

[role="code_command", subs="quotes"]
----
#Create the `SampleTodoManager` class.#
`src/main/java/io/openliberty/guides/todolistSample/managers/samples/SampleTodoManager.java`
----

SampleTodoManager.java
[source, Java, linenums, role='code_column']
----
link:finish/src/main/java/io/openliberty/guides/todolistSample/managers/samples/SampleTodoManager.java[]
----

We've implemented basic CRUD (Create, Read, Update, and Delete) operations with [hotspot=32-36]`createTodo()`, [hotspot=27-29]`getTodos()`, [hotspot=47-54]`updateTodo()` and [hotspot=60-68]`deleteTodo()`.
The SampleTodoManager is [hotspot=14 file=1]`@ApplicationScoped`, which essentially means that it is a singleton.

== Creating the JAX-RS resource


Next, we will use CDI to inject the todo manager into the resource.

[role="code_command", subs="quotes"]
----
#Create the `TodoResource` class.#
`src/main/java/io/openliberty/guides/todolistSample/resources/TodoResource.java`
----

TodoResource.java
[source, Java, linenums, role='code_column']
----
link:finish/src/main/java/io/openliberty/guides/todolistSample/resources/TodoResource.java[]
----

The resource methods are accessible via HTTP. The [hotspot]`TodoResource` class also uses [hotspot=27 hotspot=33]`@GET`, [hotspot=45]`@POST`, [hotspot=56]`@PUT`, and [hotspot=73]`@DELETE` annotations to handle reading, creating, updating, and deleting resources
The data models are validated and then send appropriate responses accordingly. For example the [hotspot=36-43]`getTodo()` method checks if [hotspot=38-40]`result.isPresent()` and sends a [hotspot=39]`Status.NOT_FOUND` response if the result is not there.
// ======================================================================================================
// END OF EXAMPLE


== Building and running the application

// Use the following include to pull in the Maven build instructions from the guides-common repo.
 include::{common-includes}/mvnbuild.adoc[]

// In between here, you should state where you application can be found now that its running. ie. urls
// Sample usage of the application
// Suggestions for what changes the reader can make to explore the code

// Use the following include to pull in the Maven rebuild instructions from the
// guides-common repo.
 include::{common-includes}/mvncompile.adoc[]



== Testing the application

// Show how to test your application.


// EXAMPLE:
======================================================================================================
[role="code_command", subs="quotes"]
----
#Create the `TodoTest` class.#
`finish/src/test/java/it/io/openliberty/guides/todo/TodoTest.java`
----

TodoTest.java
[source, Java, linenums, role='code_column']
----
link:finish/src/test/java/it/io/openliberty/guides/todolistSample/TodoTest.java[]
----

* Explain what each test case is testing
* Explain key methods
======================================================================================================

// Include this for info on how to run the tests
[role="command"]
 include::{common-includes}/mvnverify.adoc[]

// Including a listing block with test results here
// Show console output of the test results

// OPTIONAL: after listing the test results, mention a simple change a user can make/introduce that
// will cause the tests to fail. Be brief and don't give the users all of the instructions.
// At this point, they should be comfortable enough to figure it out on their own.



== Great work! You're done!

// Briefly summarize what the user achieved in this guide (1-2 sentences).

// OPTIONAL: briefly state what the user could do next now that they've learned the
// technologies in this guide.

// Include the following from the guides-common repo to tell users how they can contribute to the guide:
 include::{common-includes}/finish.adoc[]

 //Include the following guides-attribution from the guides-common repo:
link:https://raw.githubusercontent.com/OpenLiberty/guides-common/multipane/attribution.adoc[]

// DO NO CREATE ANYMORE SECTIONS AT THIS POINT
// Related guides will be added in automatically here if you included them in ":page-related-guides"