// ----------- BEGIN -----------
// Copyright (c) 2019, 2022 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//

// :projectid: paketo-buildpacks-intro
:page-layout: guide-multipane
// :page-duration: 15 minutes
// :page-releasedate: TBD
:page-description: Learn how to migrate an application using Cloud Foundry buildpacks to Paketo buildpacks. 
// :page-tags: 
// :page-permalink: /guides/{projectid}
// :page-related-guides: ['docker', 'kubernetes-intro']
// :common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/prod
// :page-guide-category: 
:page-essential: true
// :page-essential-order: 3
:source-highlighter: prettify
// :page-seo-title: 
// :page-seo-description: 
// :common-includes: ../guides-common/
// :imagesdir: /img/guide/{projectid}

// :guide-author: Open Liberty
= Migrating an application using Cloud Foundry Buildpacks to Paketo Buildpacks

You will explore how to migrate an application using Cloud Foundry liberty-for-java buildpack to using Paketo buildpacks.

// =================================================================================================
//  What you'll learn
// =================================================================================================

== What you'll learn

Learn how to migrate an application using Cloud Foundry liberty-for-java buildpack to using Paketo buildpacks. You will learn how to migrate and use advanced features of the Paketo buildpack. 

//If you're familiar with using the CF buildpacks to deploy an app

The migration includes learning how to use the following features: 

* Building with a simple `war`
* Providing server.xml at build time 
* Using different profiles (full, jakarta9, webProfile9, webProfile8, javaee8, microProfile4, microProfile5, kernel)
* Building from a Liberty Server 
* Building from a Packaged Server.
* Installing custom features 
* Installing iFixes
* Using UBI images 

== Getting Started

* https://hub.docker.com/search?type=edition&offering=community&q=[Docker]
* The https://buildpacks.io/docs/tools/pack/[pack CLI]
* Your application source. In this guide the Open Liberty starter application will be used. Use the following commands to clone the repository if needed:app-name: 

[source, console]
git clone https://github.com/openliberty/guide-getting-started.git
cd guide-getting-started/finish
 
== Building with a simple `war` 
//start with getting started blog post
//simple migration - push using a war file
//paketo.io and buildpacks.io website as references
**Walkthrough:**

Previously when using Cloud Foundry, the `war` file was pushed using the `cf push` command. 

For the Paketo Buildpacks command the process is different. After installing `Docker` and the `pack CLI`, you're ready to start building with a simple `war`. For the purpose of this tutorial, the Open Liberty starter application will be used. 

When setting the default builder from the command in the table, you'll get the following output: 

[source, console]
Builder gcr.io/paketo-buildpacks/builder:base is now the default builder

After execute the `pack build` command in the table and it will build the sample app with all of the indicated features and environments. The correct build output will give you the following message: `Successfully built image myapp`. Confirm that the features and different environment variables are present in the build. 

To run your application locally you'll execute the `docker run` command in the table. After running the command, go to your browser and navigate to: `locahost:9080`. In this case it displays the sample Open Liberty sample app or whatever your application will look like. 

[width="100%", cols="10, 10"]
[source, adoc]
|=========
|*Cloud Foundry Buildpack Commands* |*Paketo Buildpacks Commands* 
// a| Navigate to source code repository (will use Getting started app for example)
// // delete cell
// [source, console]
// git clone https://github.com/IBM-Cloud/get-started-java


  
// a| Navigate to source code repository (will use Getting started app for example)
// //delete cell
// [source, console]
// git clone https://github.com/openliberty/guide-getting-started.git
// cd guide-getting-started/finish

// a| Run app locally using command line 
// [source, console]
// cd get-started-java
// mvn clean install
// mvn install liberty:run-server

// a| Create an OCI image and run application locally
// [source, console]
// pack config default-builder gcr.io/paketo-buildpacks/builder:base

// [source, console]
// pack build --env BP_JAVA_APP_SERVER=liberty --env BP_LIBERTY_PROFILE=jakartaee9 \
//   --buildpack paketo-buildpacks/eclipse-openj9 --buildpack paketo-buildpacks/java myapp

// [source, console]
// docker run --rm -p 9080:9080 myapp


a| Push app using cloud foundry
[source, console]
cf push -p myApp.war

a| Create an OCI image and run application locally
//Say something about the pack config command what it does

The pack config command sets the default builder using the pack CLI.
[source, console]
pack config default-builder gcr.io/paketo-buildpacks/builder:base

The pack build command uses Cloud Native Buildpacks to create an app image from the source code. More info found here: https://buildpacks.io/docs/tools/pack/cli/pack_build/[pack build] 
[source, console]
pack build --env BP_JAVA_APP_SERVER=liberty 
// --env BP_LIBERTY_PROFILE=jakartaee9 \
//   --buildpack paketo-buildpacks/eclipse-openj9 --buildpack paketo-buildpacks/java myapp

[source, console]
docker run --rm -p 9080:9080 myapp
// a| Build app from an on-prem Open Liberty installation
// [source, console]
// bin/server package defaultServer --include=usr

// [source, console]
// pack build --path <packaged-server-zip-path> \
//  --buildpack paketo-buildpacks/eclipse-openj9 \
//  --buildpack paketo-buildpacks/java myapp

|=========

== Providing server.xml at build time

**Walkthrough:**

Previously when using Cloud Foundry, custom Liberty configurations are provided in the `cf push` command by installing the Liberty profile to your workstation and specifying the location in the command. 

The Paketo Buildpacks commands requires the following steps: 

The following server configuration files can be included in the application image: 

* server.xml
* server.env
* bootstrap.properties

**PLEASE NOTE:** Do not put any secrets in these configuration files! The files will be in cluded in the image and can leak your secrets. Refer to https://github.com/paketo-buildpacks/liberty#configuring-secrets[Configuring secrets] for more information on how to provide secrets in your configuration.

In the case of this starter application, to provide server configuration in the `src/main/liberty/config` directory, set one of the following variables in your `pack build` command. The command will look like this: 

`pack build app_name_here --env BP_JAVA_APP_SERVER=liberty --env BP_MAVEN_BUILT_ARTIFACT="target/*.[ejw]ar src/main/liberty/config/*"`

If successful the following message will display in the output: `Successfully built image your_app_name_here`. And to run the app locally, use the same `docker run` command as the previous section.

[width="100%", cols="10, 10"]
[source, adoc]
|=========
|*Cloud Foundry Buildpack Commands* |*Paketo Buildpacks Commands* 

a| Custom Liberty server configuration with your app

Install the Liberty profile to your workstation. Instructions found here: https://cloud.ibm.com/docs/cloud-foundry-public?topic=cloud-foundry-public-options_for_pushing#server_directory[Server directory]

Run the command:
[source, console]
cf push <yourappname> -p wlp/usr/servers/defaultServer

a| Using server.xml at build time:

Run the following commands: 

Navigate to getting-started-java directory or any sample app
[source, console]
pack config default-builder gcr.io/paketo-buildpacks/builder:base

Build the application on Liberty:
[source, console]
pack build --env BP_JAVA_APP_SERVER=liberty

When providing server configuration files like server.xml, these files can only be included in the build by telling the Maven or Gradle buildpacks to provide them. The following environment variables need to be set in your pack build command.

Server Config with Maven applications
[source, console]
--env BP_MAVEN_BUILT_ARTIFACT="target/*.[ejw]ar src/main/liberty/config/*"

Server Config with Gradle applications
[source, console]
--env BP_GRADLE_BUILT_ARTIFACT="build/libs/*.[ejw]ar src/main/liberty/config/*"

//Add a generic location for server config file. Using bindings 

Check if the server.xml file is in the directory: 
[source, console]
docker exec -it $(docker ps -q) /bin/bash

a| Binding service 

[source, console]
cf bind-service

a| Using bindings - providing server config at build and runtime

Providing server config at build-time and runtime used for secret configuration. Bindings provide credentials and location needed to connect to external services. First create the bindings/liberty folder and add the type file with liberty. Add any config you want to provide at runtime in the directory and the nmount the folder during docker run with --volume $(pwd)/bindings:/platform/bindings

[source, console]
docker run --env SERVICE_BINDING_ROOT=/bindings --volume <absolute-path-to-binding>:/bindings/<binding-name> <image-name>

|=========


== Using different profiles 
**Walkthrough:**

 In Cloud Foundry, different profiles are specified in the `cf push` command by setting the environment variables. 
 
 Similarly in the Paketo buildpack command, you can provide different profiles in the `pack build` command as referenced in the table below. Valid profiles for Open Liberty include: 

* full
* kernel
* jakartaee9
* javaee8
* webProfile8
* webProfile9
* microProfile4
* microProfile5

Valid profiles for WebSphere Liberty are: 

* kernel
* jakartaee9
* javaee8
* javaee7
* webProfile7
* webProfile8
* webProfile9

Follow the instructions in the **_Building with Simple war_** section by setting the default builder, build your application, and run it locally with the `docker run` command. For example, if you want to include jakartaee9 profile, the following command will be run: 

`pack build your_app_name_here --env BP_JAVA_APP_SERVER=liberty --env BP_LIBERTY_PROFILE=jakartaee9`

Make sure to check the console to ensure the correct profile was installed. Check the _Build Configuration_ section for a list of environment variables installed. For the `jakartaee9` profile the following can be found in the logs: 

[source, console]
----
[builder]   Build Configuration:
[builder]     $BP_JAVA_APP_SERVER       liberty     the application server to use
[builder]     $BP_LIBERTY_FEATURES                  A space separated list of liberty features to install.
[builder]     $BP_LIBERTY_INSTALL_TYPE  ol          Install type of Liberty
[builder]     $BP_LIBERTY_PROFILE       jakartaee9  The Liberty profile to install
[builder]     $BP_LIBERTY_SERVER_NAME               Name of the server to use
[builder]     $BP_LIBERTY_VERSION       *           Which version of the Liberty runtime to install
[builder]   Open Liberty (Jakarta EE9) 22.0.9: Contributing to layer
[builder]     Downloading from https://repo1.maven.org/maven2/io/openliberty/openliberty-jakartaee9/22.0.0.9/openliberty-jakartaee9-22.0.0.9.zip
[builder]     Verifying checksum
[builder]     Expanding to /layers/paketo-buildpacks_liberty/open-liberty-runtime-jakartaee9
[builder]     Installing features...
----

[width="100%", cols="10, 10"]
[source, adoc]
|=========
|*Cloud Foundry Buildpack Commands* |*Paketo Buildpacks Commands* 

a| The CF liberty-for-java buildpack allows for the following profiles to be used: javaee6, javaee7, javaee8. These profiles can be installed using the following cf commmand and environment variable: 

[source, console]
cf set-env myapp JBP_CONFIG_LIBERTY "app_archive: {features: [javaee8]}”

a| The different profiles can be installed by using the _pack build --env_ command and including the BP_LIBERTY_PROFILE environment variable. For example, to include jakartaee9 profile, the following command will be run: 

[source, console]
pack build --env BP_JAVA_APP_SERVER=liberty --env BP_LIBERTY_PROFILE=jakartaee9



|=========

== Building from a Liberty server 

**Walkthrough:**

When using CF Buildpack, a custom Liberty server can be provided by editing the `server.xml` file and placing that file by creating an `apps` directory within the `defaultServer` directory and then you can use the `cf push <yourappname> -p defaultServer`.

When using Paketo Buildpacks, the buildpack can build from a Liberty server installation directory by using the `server package` command. 

To build from a Liberty server installation, change your working directory to the installation root containing the `wlp` directory and run the following command: `pack build --env BP_JAVA_APP_SERVER=liberty myapp`

In the console you will get the following output:
//include more information here


[width="100%", cols="10, 10"]
[source, adoc]
|=========
|*Cloud Foundry Buildpack Commands* |*Paketo Buildpacks Commands* 

a| In the CF buildpacks, providing a custom Liberty server configuration requires editing the `server.xml` file. Create a `apps` directory within the `defaultServer` directory i.e. `defaultServer/apps`. In that directory a `server.xml` file can be created and placed in `defaultServer` directory. 

Once the server directory is ready the following command can be used to deploy to IBM Cloud

[source, console]
cf push <yourappname> -p defaultServer

a| The buildpack can build from a Liberty server installation directory or from a packaged server that was created using the `server package` command. More information regarding the command can be found https://openliberty.io/docs/latest/reference/command/server-package.html[here].

To build from a Liberty server installation, change your working directory to the installation root containing the `wlp` directory and run the following command: 

[source, console]
pack build --env BP_JAVA_APP_SERVER=liberty myapp

|=========

== Building from a Packaged Server

**Walkthrough:**

[width="100%", cols="10, 10"]
[source, adoc]
|=========
|*Cloud Foundry Buildpack Commands* |*Paketo Buildpacks Commands*
a| In CF buildpacks you can also push a packaged server to IBM Cloud by creating the file using Liberty's server package command. To package a Liberty server, use the `./bin/server package` command from the installed app directory. Specify the server name and include the `--include=usr` option. The CF command to package a Liberty server is the following: 

[source, console]
wlp/bin/server package server_name_here --include=usr

This command generates a `serverName.zip` file in the server's directory and the following commmand pushes the zip file to IBM Cloud:

[source, console]
cf push <yourappname> -p wlp/usr/servers/defaultServer/defaultServer.zip

a| Building from a Packaged Server: Use the `server package` command of the Liberty runtime to create a packaged server. Run the following command from Liberty installation's `wlp` directory:app-name:

[source, console]
bin/server package defaultServer --include=usr

Then the packaged server can be supplied to the build by using the `--path` argument: 
[source, console]
pack build --env BP_JAVA_APP_SERVER=liberty --path <packaged-server-zip-path> myapp

|=========

== Installing custom features

[width="100%", cols="10, 10"]
[source, adoc]
|=========
|*Cloud Foundry Buildpack Commands* |*Paketo Buildpacks Commands*
a| In CF Buildpacks, the Liberty for Java runtime includes a list of features that are available in Liberty. You can install features that aren't included in the runtime by running the `installUtility` command as a pre-runtime hook when the app is being pushed to IBM Cloud i.e. adding MicroProfile Config 3.0. 

1. In the root directory of the app, create a `.profile.d` directory. Use the `.profile.d` feature to copy the manifest and feature jar to the user feature path and user bundle path

2. Modify the `server.xml` to enable the user feature

// [source, console]
// ----
// #!/bin/sh
// echo "Installing audit-1.0"
// export PATH=$PATH:$HOME/app/.java/jre/bin

// $HOME/app/.liberty/bin/installUtility install audit-1.0 --acceptLicense
// ----
a| **Using Custom Features:** Custom features can can either be configured on the server or using a volume mount to `/features` that contains the feature JARs and manifests along with a feature descriptor.

**Feature Manifest:** The feature manifest is a `features.toml` file containing a list of `features` that would be installed on the server.

A feature has the following properties:
[disc]
* `name`: Name of the feature to enable. Use symbolic name of the feature that you would use when enabling the feature in the `server.xml`
* `uri`: URI of where to find the fetaure. The `file` scheme is the only supported scheme at the moment.
* `version`: Version of the feature
* `dependencies`: List of features that the custom feature depends on

**Example Feature Manifest**: This example shows how to configure a feature called `dummyCache` that has a dependency `distributedMap-1.0` feature. Any additional features added will use the same format as the example below.

First create the feature descriptor `features.toml` with the following content:
[source, toml]
----
[[features]]
  name = "dummyCache"
  uri = "file://features/cache.dummy_1.0.0.jar"
  version = "1.0.0"
  dependencies = ["distributedMap-1.0"]
----

Using the above feature description, the Liberty buildpack will look for the feature JAR in the volume mounted on `/features` at the path `features/cache.dummy_1.0.0.jar`. The buildpack also assumes that the feature manifest file will be at the path `features/cache.dummy_1.0.0.mf`. 
//***QUESTION*** here regarding the guide

After creating the feature descriptor, tar and gzip the `feature.toml` and `features` directory so that it has the contents similar to the following: 

[source, console]
----
$ tar tzf liberty-conf.tar.gz
./
./features/
./features.toml
./features/cache.dummy_1.0.0.mf
./features/cache.dummy_1.0.0.jar
----

Then, the custom features can be provided to the build by mounting the feature directory to `/features`:
[source, console]
pack build --path myapp --env BP_JAVA_APP_SERVER=liberty --volume /Users/userNameHere/Development/paketo-buildpacks/liberty-e2e.bak/data/conf/features:/features myapp

|=========

== Installing iFixes 

[width="100%", cols="10, 10"]
[source, adoc]
|=========
|*Cloud Foundry Buildpack Commands* |*Paketo Buildpacks Commands*

a| **Applying iFix to the Liberty runtime**:

An iFix can be applied to an app using the `.profile.d` feature.

* Create the `.profile.d/.ifixes` directory in the root of the app that's being deployed to IBM Cloud
* Place the iFix `.jar` file in the `.profile.d/.ifixes/` directory
* Create `ifix.sh` file in the `.profile.d` directory with the following contents (update the <ifix filename> accordingly)
* If the iFix file can celany apply against the IBM Cloud version of Liberty, use the following script: 

[source, console]
#!/bin/sh
echo "Applying iFixes"
$HOME/.java/jre/bin/java -jar $HOME/.profile.d/.ifixes/<ifix filename>.jar --installLocation $HOME/.liberty/

* If the iFix file cannot cleanly apply, use the following script: 

[source, console]
#!/bin/sh
echo "Applying iFixes"
unzip $HOME/.profile.d/.ifixes/<ifix filename>.jar lib/*.jar -d $HOME/.liberty

For example, the contents of the `.profile.d` directory should look like the following: 

[source, console]
.profile.d/
.profile.d/.ifixes/16003-wlp-archive-IFPI68805.jar
.profile.d/ifix.sh

Once you deploy your application, you should see the following message that indicates which iFixes were applied:

[source, console]
CWWKF0015I: The server has the following interim fixes active in the runtime: PIXXXXX. For a full listing of installed fixes run: productInfo version --ifixes

a| **How to apply an iFix to the Liberty runtime**

An iFix can be applied to the liberty runtime using a volume mount. 

There are the following requirements to install iFixes: 

* Only the archive versions of Liberty iFixes are supported 
* The iFixes are in a directory named `ifixes`

For example the contents of the `ifixes` directory should look like the following:

[source, console]
ifixes/
ifixes/220002-wlp-archive-ifph12345.jar
ifixes/220002-wlp-archive-ifph67890.jar

Specify the `--volume` parameter mapping your local `ifixes/` directory to `/ifixes` in the container

[source, console]
pack build myapp --env BP_JAVA_APP_SERVER=liberty --volume /path/to/ifixes:/ifixes

The build output will show the iFix being applied: 

[source, console]
[builder]   Open Liberty (All Features) 22.0.3: Contributing to layer
[builder]     Downloading from https://repo1.maven.org/maven2/io/openliberty/openliberty-runtime/22.0.0.3/openliberty-runtime-22.0.0.3.zip
[builder]     Verifying checksum
[builder]     Expanding to /layers/paketo-buildpacks_liberty/open-liberty-runtime-full
[builder]     Installing iFix 22003-wlp-archive-ifph44666.jar
[builder]       Applying fix to Liberty install directory at /layers/paketo-buildpacks_liberty/open-liberty-runtime-full now.
[builder]       	lib/com.ibm.ws.openapi.ui.private_1.0.62.cl220320220308-1516.jar
[builder]       	lib/com.ibm.ws.openapi.ui_1.0.62.cl220320220308-1516.jar
[builder]       	lib/com.ibm.ws.microprofile.openapi.ui_1.0.62.cl220320220308-1516.jar
[builder]       Fix has been applied successfully.
[builder]       Successfully extracted all product files.
|=========

== Using UBI images 
[width="100%", cols="10, 10"]
[source, adoc]
|=========
|*Cloud Foundry Buildpack Commands* |*Paketo Buildpacks Commands*
a| Push a Docker Image from a Registry:

Cloud Foundry supports pushign apps from container registries such as Docker Hub, Google Container Registry (GCR), and Amazon Elastic Container Registry (ECR).

How you run `cf push` with apps stored in container

[source, console]
cf push APP-NAME --docker-image REPO/IMAGE:TAG

More reference information on pushing an app in CF using a docker image can be found here: https://docs.cloudfoundry.org/devguide/deploy-apps/push-docker.html[Deploying an App with Docker]

a| Using a Liberty Runtime Provided in the Stack Run Image

**Creating the Stack Image:**

Create the following script: 

[source, console]
#!/usr/bin/env bash
main() {
  readonly LIBERTY_USR_DIRS=(
    "/workspace/wlp/usr"
    "/workspace/usr"
    "/layers/paketo-buildpacks_liberty/base/wlp/usr"
  )
  for liberty_usr_dir in "${LIBERTY_USR_DIRS[@]}"; do
    if [[ -d "${liberty_usr_dir}" ]]; then
      local usr_dir="${liberty_usr_dir}"
      break
    fi
  done
  cp -rf "${usr_dir}/." "${BPI_LIBERTY_RUNTIME_ROOT}/usr/"
  # Call Liberty runtime's bootstrap script
  docker-server.sh "${@}"
}
main "${@}"

**Building the stack images:**

After preparing the `Dockerfile` for the stack, use the following commands to build the run and build images that will be used: 

[source, console]
docker build -t <image-name>-run:latest --target run .
docker build -t <image-name>-build:latest --target build .

Replace `<image-name` with whatever image name you would like to use.

**Deploying a Liberty application:**

Use the following command with custom stack images and builder specified:

[source, console]
$ pack build myapp --builder mybuilder:latest --env BP_LIBERTY_INSTALL_TYPE="none"

|=========








// ------------ END ------------