// ----------- BEGIN -----------
// Copyright (c) 2019, 2022 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//

// :projectid: paketo-buildpacks-intro
:page-layout: guide-multipane
// :page-duration: 15 minutes
// :page-releasedate: TBD
:page-description: Learn how to migrate an application using Cloud Foundry buildpacks to Paketo buildpacks. 
// :page-tags: 
// :page-permalink: /guides/{projectid}
// :page-related-guides: ['docker', 'kubernetes-intro']
// :common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/prod
// :page-guide-category: 
:page-essential: true
// :page-essential-order: 3
:source-highlighter: prettify
// :page-seo-title: 
// :page-seo-description: 
// :common-includes: ../guides-common/
// :imagesdir: /img/guide/{projectid}

// :guide-author: Open Liberty
= Migrating an application using Cloud Foundry Buildpacks to Paketo Buildpacks

You will explore how to migrate an application using Cloud Foundry liberty-for-java buildpack to using Paketo buildpacks.

// =================================================================================================
//  What you'll learn
// =================================================================================================

== What you'll learn

Learn how to migrate an application using Cloud Foundry liberty-for-java buildpack to using Paketo buildpacks. You will learn how to migrate and use advanced features of the Paketo buildpack. 

//If you're familiar with using the CF buildpacks to deploy an app

The migration includes learning how to use the following features: 

* Building with a simple `war`
* Providing server.xml at build time 
* Using different profiles (full, jakarta9, webProfile9, webProfile8, javaee8, microProfile4, microProfile5, kernel)
* Building from a Liberty Server 
* Building from a Packaged Server.
* Installing custom features 
* Installing iFixes
* Using UBI images 

== Getting Started

The following are the prerequisites needed to go through this migration guide. 

* https://hub.docker.com/search?type=edition&offering=community&q=[Docker]
* The https://buildpacks.io/docs/tools/pack/[pack CLI]
* If you're new to buildpacks, I recommend you set a default builder as this removes the need to set a builder each time you build an image: 
`pack config default-builder gcr.io/paketo-buildpacks/builder:base`
* JDK 
* Your application source. In this guide the Open Liberty starter application will be used to demonstrate each of the features. Use the following commands to clone the repository and download the Open Liberty starter application: 


[source, console]
git clone https://github.com/openliberty/guide-getting-started.git
cd guide-getting-started/finish
 
== Building with a simple `war` 
//start with getting started blog post
//simple migration - push using a war file
//paketo.io and buildpacks.io website as references
**Walkthrough:**
//Be mindful of consistent use of font and color commands vs output
Previously when using Cloud Foundry, the `war` file was pushed using the `cf push` command. 

For the Paketo Buildpacks command the process is different. After installing `Docker`, `pack CLI`, and JDK in the Getting Started section, you are ready to start building with a simple `war` file. For the purpose of this tutorial, the Open Liberty starter application will be used.

//indicate just finish directory 
You are now ready to build the application. For this starter app, navigate to either the `finish` or `start` directory. To generate a `.war` file run the following command: `mvn install` in the app's `finish` directory. It will generate a `guide-getting-started.war` file in the `target` directory.

Once the `.war` file is generated, you can set the default builder, the following `pack config` command will be used: 

`pack config default-builder gcr.io/paketo-buildpacks/builder:base`. 

After running the `pack config` command you will get the following output: 

[source, console]
Builder gcr.io/paketo-buildpacks/builder:base is now the default builder

After this command, you can execute the `pack build` command. Make sure to include the `--path` to where the `.war` file was installed and include the `--buildpack` option the build uses the OpenJ9 `--buildpack paketo-buildpacks/eclipse-openj9 --buildpack paketo-buildpacks/java`. The complete `pack build` command will be the following:
//openj9 JRE

`pack build your_app_name_here --env BP_JAVA_APP_SERVER=liberty src/main/liberty/config/*" --buildpack paketo-buildpacks/eclipse-openj9 --buildpack paketo-buildpacks/java --path target/guide-getting-started.war`

It will build the sample app with all of the indicated features and environments. Confirm that the features and different environment variables are present in the build. After running command verify that the paketo-buildpacks are being used in the DETECTING section. Then ensure that the correct "Build Configuration" is being used. A sample output of the `pack build` command will be the following: 

[source, console]
----
===> DETECTING
[detector] 7 of 25 buildpacks participating
[detector] paketo-buildpacks/eclipse-openj9    9.7.0
[detector] paketo-buildpacks/ca-certificates   3.4.0
[detector] paketo-buildpacks/bellsoft-liberica 9.8.0
[detector] paketo-buildpacks/syft              1.20.0
[detector] paketo-buildpacks/liberty           2.2.0
[detector] paketo-buildpacks/dist-zip          5.4.0
[detector] paketo-buildpacks/spring-boot       5.19.0
...
===> BUILDING
[builder]
[builder] Paketo Eclipse OpenJ9 Buildpack 9.7.0
[builder]   https://github.com/paketo-buildpacks/eclipse-openj9
[builder]   Build Configuration:
[builder]     $BP_JVM_JLINK_ARGS           --no-man-pages --no-header-files --strip-debug --compress=1  configure custom link arguments (--output must be omitted)
[builder]     $BP_JVM_JLINK_ENABLED        false                                                        enables running jlink tool to generate custom JRE
[builder]     $BP_JVM_TYPE                 JRE                                                          the JVM type - JDK or JRE
[builder]     $BP_JVM_VERSION              11                                                           the Java version
[builder]   Launch Configuration:
[builder]     $BPL_DEBUG_ENABLED           false                                                        enables Java remote debugging support
[builder]     $BPL_DEBUG_PORT              8000                                                         configure the remote debugging port
[builder]     $BPL_DEBUG_SUSPEND           false                                                        configure whether to suspend execution until a debugger has attached
[builder]     $BPL_HEAP_DUMP_PATH                                                                       write heap dumps on error to this path
[builder]     $BPL_JMX_ENABLED             false                                                        enables Java Management Extensions (JMX)
[builder]     $BPL_JMX_PORT                5000                                                         configure the JMX port
[builder]     $BPL_JVM_HEAD_ROOM           0                                                            the headroom in memory calculation
[builder]     $BPL_JVM_LOADED_CLASS_COUNT  35% of classes                                               the number of loaded classes in memory calculation
[builder]     $BPL_JVM_THREAD_COUNT        250                                                          the number of threads in memory calculation
[builder]     $JAVA_TOOL_OPTIONS                                                                        the JVM launch flags
[builder]     Using Java version 11 extracted from MANIFEST.MF
[builder]   OpenJ9 JDK 11.0.16: Reusing cached layer
[builder]   OpenJ9 JRE 11.0.16: Reusing cached layer
[builder]   Launch Helper: Reusing cached layer
[builder]   Java Security Properties: Reusing cached layer
[builder]
[builder] Paketo Buildpack for CA Certificates 3.4.0
[builder]   https://github.com/paketo-buildpacks/ca-certificates
[builder]   Launch Helper: Reusing cached layer
[builder]
[builder] Paketo Buildpack for Syft 1.20.0
[builder]   https://github.com/paketo-buildpacks/syft
[builder]
[builder] Paketo Buildpack for Liberty 2.2.0
[builder]   https://github.com/paketo-buildpacks/liberty
...
Successfully built image myapp
----

The correct build output from the `pack build` command will give you the following message at the end of: `Successfully built image myapp`. 

After running and verifying the output of the `pack build` command, to run your application locally you'll execute the following `docker run` command: 

`docker run --rm -p 9080:9080 your_app_name_here`

After running the command, go to your browser and navigate to: `locahost:9080`. In this case it displays the sample Open Liberty sample app or whatever your application will look like. For this sample app the following message will display: "Congrats on your shiny, new Open Liberty sample app!".

Refer to the table below for more information regarding the commands and the comparison between the Cloud Foundry buildpack commands versus the Paketo Buildpack commands.

[width="100%", cols="10, 10"]
[source, adoc]
|=========
|*Cloud Foundry Buildpack Commands* |*Paketo Buildpacks Commands* 
// a| Navigate to source code repository (will use Getting started app for example)
// // delete cell
// [source, console]
// git clone https://github.com/IBM-Cloud/get-started-java


  
// a| Navigate to source code repository (will use Getting started app for example)
// //delete cell
// [source, console]
// git clone https://github.com/openliberty/guide-getting-started.git
// cd guide-getting-started/finish

// a| Run app locally using command line 
// [source, console]
// cd get-started-java
// mvn clean install
// mvn install liberty:run-server

// a| Create an OCI image and run application locally
// [source, console]
// pack config default-builder gcr.io/paketo-buildpacks/builder:base

// [source, console]
// pack build --env BP_JAVA_APP_SERVER=liberty --env BP_LIBERTY_PROFILE=jakartaee9 \
//   --buildpack paketo-buildpacks/eclipse-openj9 --buildpack paketo-buildpacks/java myapp

// [source, console]
// docker run --rm -p 9080:9080 myapp


a| Push app using cloud foundry
[source, console]
cf push -p myApp.war

a| Create an OCI image and run application locally

//Only have to do the `pack config` command once.

// The pack config command sets the default builder using the pack CLI.
// [source, console]
// pack config default-builder gcr.io/paketo-buildpacks/builder:base

The pack build command uses Cloud Native Buildpacks to create an app image from the source code. More info found here: https://buildpacks.io/docs/tools/pack/cli/pack_build/[pack build] 
[source, console]
pack build myapp --env BP_JAVA_APP_SERVER=liberty --env BP_MAVEN_BUILT_ARTIFACT="target/*.war src/main/liberty/config/*" --buildpack paketo-buildpacks/eclipse-openj9 --buildpack paketo-buildpacks/java --path target/guide-getting-started.war

[source, console]
docker run --rm -p 9080:9080 myapp
// a| Build app from an on-prem Open Liberty installation
// [source, console]
// bin/server package defaultServer --include=usr

// [source, console]
// pack build --path <packaged-server-zip-path> \
//  --buildpack paketo-buildpacks/eclipse-openj9 \
//  --buildpack paketo-buildpacks/java myapp

|=========

== Providing server.xml at build time

**Walkthrough:**

Previously when using Cloud Foundry, custom Liberty configurations are provided in the `cf push` command by installing the Liberty profile to your workstation and specifying the location in the command. 

The Paketo Buildpacks commands requires following the steps as outlined below: 

The following server configuration files can be included in the application image: 

* server.xml
* server.env
* bootstrap.properties

**PLEASE NOTE:** Do not put any secrets in these configuration files! The files will be in cluded in the image and can leak your secrets. Refer to https://github.com/paketo-buildpacks/liberty#configuring-secrets[Configuring secrets] for more information on how to provide secrets in your configuration.

In the case of this starter application, to provide server configuration in the `src/main/liberty/config` directory, set one of the following variables in your `pack build` command. These files can only be included in the build by telling the Maven or Gradle buildpacks to provide them. If the Server configuration is provided with Maven applications then the command will look like this: 

`pack build app_name_here --env BP_JAVA_APP_SERVER=liberty --env BP_MAVEN_BUILT_ARTIFACT="target/*.[ejw]ar src/main/liberty/config/*" --buildpack paketo-buildpacks/eclipse-openj9 --buildpack paketo-buildpacks/java`

If the server configuration is provided with Gradle applications the command will be the following: 

`pack build app_name_here --env BP_JAVA_APP_SERVER=liberty --env BP_GRADLE_BUILT_ARTIFACT="build/libs/*.[ejw]ar src/main/liberty/config/*"`

If successful the following message will display in the output: `Successfully built image your_app_name_here`. Also a warning message regarding the `server.xml` config file will appear in the output: "Reminder: Do not include secrets in server.xml; this file has been included in the image and that can leak your secrets". The build output will look like the following: 

[source, console]
----
...
[builder] Paketo Buildpack for Liberty 2.2.0
[builder]   https://github.com/paketo-buildpacks/liberty
[builder]   Build Configuration:
[builder]     $BP_JAVA_APP_SERVER       liberty  the application server to use
[builder]     $BP_LIBERTY_FEATURES               A space separated list of liberty features to install.
[builder]     $BP_LIBERTY_INSTALL_TYPE  ol       Install type of Liberty
[builder]     $BP_LIBERTY_PROFILE                The Liberty profile to install
[builder]     $BP_LIBERTY_SERVER_NAME            Name of the server to use
[builder]     $BP_LIBERTY_VERSION       *        Which version of the Liberty runtime to install
[builder]   Launch Configuration:
[builder]     $BPL_LIBERTY_LOG_LEVEL             Sets the logging level
[builder]     $BP_LIBERTY_CONTEXT_ROOT           Context root to use for app
[builder]     $BP_LIBERTY_SERVER_NAME            Name of the server to use
[builder] Warning: The default profile for Open Liberty will change from 'full' to 'kernel' after 2022-11-01. To continue using the full profile, build with the argument '--env BP_LIBERTY_PROFILE=full'
[builder]   Launch Helper: Reusing cached layer
[builder]   Open Liberty Config: Contributing to layer
[builder] Reminder: Do not include secrets in server.xml; this file has been included in the image and that can leak your secrets
...
----

And to run the app locally, use the same `docker run` command as the previous section:

`docker run --rm -p 9080:9080 myapp`

Further background information can be found in the table below.

[width="100%", cols="10, 10"]
[source, adoc]
|=========
|*Cloud Foundry Buildpack Commands* |*Paketo Buildpacks Commands* 

a| Custom Liberty server configuration with your app

Install the Liberty profile to your workstation. Instructions found here: https://cloud.ibm.com/docs/cloud-foundry-public?topic=cloud-foundry-public-options_for_pushing#server_directory[Server directory]

Run the command:
[source, console]
cf push <yourappname> -p wlp/usr/servers/defaultServer

a| Using server.xml at build time:

Run the following commands: 

Build the application on Liberty:
[source, console]
pack build app_name_here --env BP_JAVA_APP_SERVER=liberty --env BP_MAVEN_BUILT_ARTIFACT="target/*.[ejw]ar src/main/liberty/config/*" --buildpack paketo-buildpacks/eclipse-openj9 --buildpack paketo-buildpacks/java

When providing server configuration files like server.xml, these files can only be included in the build by telling the Maven or Gradle buildpacks to provide them. The following environment variables need to be set in your pack build command.

Server Config with Maven applications
[source, console]
--env BP_MAVEN_BUILT_ARTIFACT="target/*.[ejw]ar src/main/liberty/config/*"

Server Config with Gradle applications
[source, console]
--env BP_GRADLE_BUILT_ARTIFACT="build/libs/*.[ejw]ar src/main/liberty/config/*"

a| Binding service 

[source, console]
cf bind-service

a| Using bindings - providing server config at build and runtime

Providing server config at build-time and runtime used for secret configuration. Bindings provide credentials and location needed to connect to external services. First create the bindings/liberty folder and add the type file with liberty. Add any config you want to provide at runtime in the directory and the nmount the folder during docker run with --volume $(pwd)/bindings:/platform/bindings

[source, console]
docker run --env SERVICE_BINDING_ROOT=/bindings --volume <absolute-path-to-binding>:/bindings/<binding-name> <image-name>

|=========


== Using different profiles 
**Walkthrough:**

 In Cloud Foundry, different profiles are specified in the `cf push` command by setting the environment variables. 
 
 Similarly in the Paketo buildpack command, you can provide different profiles in the `pack build` command as referenced in the table below. Valid profiles for Open Liberty include: 

* full
* kernel
* jakartaee9
* javaee8
* webProfile8
* webProfile9
* microProfile4
* microProfile5

Valid profiles for WebSphere Liberty are: 

* kernel
* jakartaee9
* javaee8
* javaee7
* webProfile7
* webProfile8
* webProfile9

Follow the instructions in the **_Building with Simple war_** section by setting the default builder, running the `mvn clean` and `mvn install` commands, `pack build` command, and run it locally with the `docker run` command. For example, if you want to include jakartaee9 profile, the following command will be run: 

`pack build your_app_name_here --env BP_JAVA_APP_SERVER=liberty --env BP_LIBERTY_PROFILE=jakartaee9 src/main/liberty/config/*" --buildpack paketo-buildpacks/eclipse-openj9 --buildpack paketo-buildpacks/java`

Make sure to check the console to ensure the correct profile was installed. Check the _Build Configuration_ section for a list of environment variables installed. For the `jakartaee9` profile the following can be found in the logs under the Build Configuration steps for **Paketo Buildpack for Liberty 2.2.0**: 

[source, console]
----
...
[builder] Paketo Buildpack for Liberty 2.2.0
[builder]   https://github.com/paketo-buildpacks/liberty
[builder]   Build Configuration:
[builder]     $BP_JAVA_APP_SERVER       liberty     the application server to use
[builder]     $BP_LIBERTY_FEATURES                  A space separated list of liberty features to install.
[builder]     $BP_LIBERTY_INSTALL_TYPE  ol          Install type of Liberty
[builder]     $BP_LIBERTY_PROFILE       jakartaee9  The Liberty profile to install
[builder]     $BP_LIBERTY_SERVER_NAME               Name of the server to use
[builder]     $BP_LIBERTY_VERSION       *           Which version of the Liberty runtime to install
[builder]   Launch Configuration:
[builder]     $BPL_LIBERTY_LOG_LEVEL                Sets the logging level
[builder]     $BP_LIBERTY_CONTEXT_ROOT              Context root to use for app
[builder]     $BP_LIBERTY_SERVER_NAME               Name of the server to use
...
----

Any profiles can be added to the `pack build` command with the `--env BP_LIBERTY_PROFILE` option.

[width="100%", cols="10, 10"]
[source, adoc]
|=========
|*Cloud Foundry Buildpack Commands* |*Paketo Buildpacks Commands* 

a| The CF liberty-for-java buildpack allows for the following profiles to be used: javaee6, javaee7, javaee8. These profiles can be installed using the following cf commmand and environment variable: 

[source, console]
cf set-env myapp JBP_CONFIG_LIBERTY "app_archive: {features: [javaee8]}”

a| The different profiles can be installed by using the _pack build --env_ command and including the BP_LIBERTY_PROFILE environment variable. For example, to include jakartaee9 profile, the following command will be run: 

[source, console]
pack build your_app_name_here --env BP_JAVA_APP_SERVER=liberty --env BP_LIBERTY_PROFILE=jakartaee9 src/main/liberty/config/*" --buildpack paketo-buildpacks/eclipse-openj9 --buildpack paketo-buildpacks/java


|=========

== Building from a Liberty server 

**Walkthrough:**

//the buildpack can push
When using the CF Buildpack, the buildpack can push a custom Liberty server configuration using the `cf push` command.

When using Paketo Buildpacks, the buildpack can build from an existing Liberty server installation directory. 
// Then execute the following initial set-up steps including: installing a Liberty server from https://openliberty.io/start/[Open Liberty], creating and starting the server using the `server` command, and updating the `server.xml` and `.war` file. 

After the initial setup of the Liberty server, build from a Liberty server installation by changing your working directory to the installation root containing the `wlp` directory and running the following command: 

`pack build --env BP_JAVA_APP_SERVER=liberty --buildpack paketo-buildpacks/eclipse-openj9 --buildpack paketo-buildpacks/java sampleapp`

The build output will be similar to the previous section with the **liberty** server indicated in the BP_JAVA_APP_SERVER option: 

//modify build output.

[source, console]
----
...
[builder] Paketo Buildpack for Liberty 2.2.0
[builder]   https://github.com/paketo-buildpacks/liberty
[builder]   Build Configuration:
[builder]     $BP_JAVA_APP_SERVER       liberty  the application server to use
[builder]     $BP_LIBERTY_FEATURES               A space separated list of liberty features to install.
[builder]     $BP_LIBERTY_INSTALL_TYPE  ol       Install type of Liberty
[builder]     $BP_LIBERTY_PROFILE                The Liberty profile to install
[builder]     $BP_LIBERTY_SERVER_NAME   server1  Name of the server to use
[builder]     $BP_LIBERTY_VERSION       *        Which version of the Liberty runtime to install
[builder]   Launch Configuration:
[builder]     $BPL_LIBERTY_LOG_LEVEL             Sets the logging level
[builder]     $BP_LIBERTY_CONTEXT_ROOT           Context root to use for app
[builder]     $BP_LIBERTY_SERVER_NAME   server1  Name of the server to use
...
Successfully built image sampleapp
----

A successful build will also contain the following message: "Successfully built image sampleapp".


[width="100%", cols="10, 10"]
[source, adoc]
|=========
|*Cloud Foundry Buildpack Commands* |*Paketo Buildpacks Commands* 

a| In the CF buildpacks, providing a custom Liberty server configuration requires editing the `server.xml` file. Create a `apps` directory within the `defaultServer` directory i.e. `defaultServer/apps`. In that directory a `server.xml` file can be created and placed in `defaultServer` directory. 

Once the server directory is ready the following command can be used to deploy to IBM Cloud

[source, console]
cf push <yourappname> -p defaultServer

a| The buildpack can build from a Liberty server installation directory or from a packaged server that was created using the `server package` command. More information regarding the command can be found https://openliberty.io/docs/latest/reference/command/server-package.html[here].

To build from a Liberty server installation, change your working directory to the installation root containing the `wlp` directory and run the following command: 

[source, console]
pack build --env BP_JAVA_APP_SERVER=liberty --buildpack paketo-buildpacks/eclipse-openj9 --buildpack paketo-buildpacks/java sampleapp`

|=========

== Building from a Packaged Server

**Walkthrough:**

When using Cloud Foundry Buildpacks the `./bin/server package` was used to generate a packaged server. 

When using Paketo Buildpacks, the process of creating a packaged server is the same. Use the following `server package` command from the Liberty installation's directory to create a packaged server:

`bin/server package your-app-server-name --include=usr`

The output of the command will look like this: 

[source console]
----
Packaging server server1.
Server your-app-server-name package complete in directory-for-server-zip
----

The packaged server can then be supplied to the build by specifying it in the `--path` argument:

`pack build --env BP_JAVA_APP_SERVER=liberty --buildpack paketo-buildpacks/eclipse-openj9 --buildpack paketo-buildpacks/java --path usr/servers/your-app-server-name/your-app-server-name.zip sampleapp2`

// `pack build --env BP_JAVA_APP_SERVER=liberty --buildpack paketo-buildpacks/eclipse-openj9 --buildpack paketo-buildpacks/java --path usr/servers/server1/server1.zip sampleapp2`

The following will be the build output: 

[source, console]
----
...
[builder] Paketo Buildpack for Liberty 2.2.0
[builder]   https://github.com/paketo-buildpacks/liberty
[builder]   Build Configuration:
[builder]     $BP_JAVA_APP_SERVER       liberty  the application server to use
[builder]     $BP_LIBERTY_FEATURES               A space separated list of liberty features to install.
[builder]     $BP_LIBERTY_INSTALL_TYPE  ol       Install type of Liberty
[builder]     $BP_LIBERTY_PROFILE                The Liberty profile to install
[builder]     $BP_LIBERTY_SERVER_NAME            Name of the server to use
[builder]     $BP_LIBERTY_VERSION       *        Which version of the Liberty runtime to install
[builder]   Launch Configuration:
[builder]     $BPL_LIBERTY_LOG_LEVEL             Sets the logging level
[builder]     $BP_LIBERTY_CONTEXT_ROOT           Context root to use for app
[builder]     $BP_LIBERTY_SERVER_NAME            Name of the server to use
[builder] Warning: The default profile for Open Liberty will change from 'full' to 'kernel' after 2022-11-01. To continue using the full profile, build with the argument '--env BP_LIBERTY_PROFILE=full'
[builder]   Launch Helper: Contributing to layer
[builder]     Creating /layers/paketo-buildpacks_liberty/helper/exec.d/linker
[builder]   Open Liberty Config: Contributing to layer
[builder]     Writing env.launch/BPI_LIBERTY_SERVER_NAME.default
[builder]     Writing env.launch/WLP_USER_DIR.default
[builder]   Open Liberty (All Features) 22.0.9: Contributing to layer
[builder]     Downloading from https://repo1.maven.org/maven2/io/openliberty/openliberty-runtime/22.0.0.9/openliberty-runtime-22.0.0.9.zip
...
----


[width="100%", cols="10, 10"]
[source, adoc]
|=========
|*Cloud Foundry Buildpack Commands* |*Paketo Buildpacks Commands*
a| In CF buildpacks you can also push a packaged server to IBM Cloud by creating the file using Liberty's server package command. To package a Liberty server, use the `./bin/server package` command from the installed app directory. Specify the server name and include the `--include=usr` option. The Liberty command to package a Liberty server is the following: 

[source, console]
wlp/bin/server package server_name_here --include=usr

This command generates a `serverName.zip` file in the server's directory and the following commmand pushes the zip file to IBM Cloud:

[source, console]
cf push <yourappname> -p wlp/usr/servers/defaultServer/serverName.zip

a| Building from a Packaged Server: 

Use the `server package` command of the Liberty runtime to create a packaged server. Run the following command from Liberty installation's `wlp`

[source, console]
bin/server package defaultServer --include=usr

Then the packaged server can be supplied to the build by using the `--path` argument: 
[source, console]
pack build --env BP_JAVA_APP_SERVER=liberty --path <packaged-server-zip-path> myapp

|=========

== Installing custom features

**Walkthrough:**

//Include brief summary of CF Buildpacks installing custom features

In Paketo Buildpacks, custom features are configured using a volume mount to the `/features` directory that contains the feature JARs, manifests, and feature descriptor. 

The feature manifest is a TOML file called `features.toml` file containing a list of features that would be installed on the server.

A feature has the following properties:
[disc]
* `name`: Name of the feature to enable. Use symbolic name of the feature that you would use when enabling the feature in the `server.xml`
* `uri`: URI of where to find the fetaure. The `file` scheme is the only supported scheme at the moment.
* `version`: Version of the feature
* `dependencies`: List of features that the custom feature depends on

For this walkthrough, an example feature, `jar`, and `.mf` file will be used. 

First, create the `features.toml` file with the following content: 

[source, console]
----
[[features]]
  name = "dummyCache"
  uri = "file://features/cache.dummy_1.0.0.jar"
  version = "1.0.0"
  dependencies = ["distributedMap-1.0"]
----

Then in the `features` directory, include the `features.toml`, `cache.dummy_1.0.0.mf`, and `cache.dummy_1.0.0.jar` and gzip the entire directory like so: 

[source, console]
$ tar czvf features.tar.gz *
./
./features/
./features.toml
./features/cache.dummy_1.0.0.mf
./features/cache.dummy_1.0.0.jar

The custom features can then be used in the build in the following command by mounting the feature directory to `/features`.

`pack build --env BP_JAVA_APP_SERVER=liberty --volume path-to-features-directory:/features --buildpack paketo-buildpacks/eclipse-openj9 --buildpack paketo-buildpacks/java myapp`

A successful build output should contain the following in the `Paketo Buildpack for Liberty` section: 

[source, console]
----
...
[builder] Paketo Buildpack for Liberty 2.2.0
[builder]   https://github.com/paketo-buildpacks/liberty
[builder]   Build Configuration:
[builder]     $BP_JAVA_APP_SERVER       liberty  the application server to use
[builder]     $BP_LIBERTY_FEATURES               A space separated list of liberty features to install.
[builder]     $BP_LIBERTY_INSTALL_TYPE  ol       Install type of Liberty
[builder]     $BP_LIBERTY_PROFILE                The Liberty profile to install
[builder]     $BP_LIBERTY_SERVER_NAME            Name of the server to use
[builder]     $BP_LIBERTY_VERSION       *        Which version of the Liberty runtime to install
[builder]   Launch Configuration:
[builder]     $BPL_LIBERTY_LOG_LEVEL             Sets the logging level
[builder]     $BP_LIBERTY_CONTEXT_ROOT           Context root to use for app
[builder]     $BP_LIBERTY_SERVER_NAME            Name of the server to use
[builder] Warning: The default profile for Open Liberty will change from 'full' to 'kernel' after 2022-11-01. To continue using the full profile, build with the argument '--env BP_LIBERTY_PROFILE=full'
[builder]   Launch Helper: Reusing cached layer
[builder]   Open Liberty Config: Contributing to layer
[builder]     Writing env.launch/BPI_LIBERTY_SERVER_NAME.default
[builder]     Writing env.launch/WLP_USER_DIR.default
[builder]   Open Liberty (All Features) 22.0.9: Contributing to layer
[builder]     Downloading from https://repo1.maven.org/maven2/io/openliberty/openliberty-runtime/22.0.0.9/openliberty-runtime-22.0.0.9.zip
[builder]     Verifying checksum
[builder]     Expanding to /layers/paketo-buildpacks_liberty/open-liberty-runtime-full
[builder]     Installing features...
[builder]       Initializing ...
[builder]       Using 8 threads to download artifacts.
[builder]       Resolving remote features. This process might take several minutes to complete.
[builder]       The server does not require any additional features. No features were installed.
[builder]       Start product validation...
[builder]       Product validation completed successfully.
[builder]     Writing env.launch/BPI_LIBERTY_RUNTIME_ROOT.default
[builder]     Writing env.launch/BPL_JVM_CLASS_ADJUSTMENT.default
[builder]     Writing env.launch/WLP_LOGGING_APPS_WRITE_JSON.default
[builder]     Writing env.launch/WLP_LOGGING_CONSOLE_FORMAT.default
[builder]     Writing env.launch/WLP_LOGGING_CONSOLE_SOURCE.default
[builder]     Writing env.launch/WLP_LOGGING_JSON_ACCESS_LOG_FIELDS.default
[builder]     Writing env.launch/WLP_LOGGING_MESSAGE_FORMAT.default
[builder]     Writing env.launch/WLP_LOGGING_MESSAGE_SOURCE.default
[builder]     Writing env.launch/WLP_OUTPUT_DIR.override
[builder]   Process types:
[builder]     open-liberty-runtime: server run defaultServer (direct)
...
----

[width="100%", cols="10, 10"]
[source, adoc]
|=========
|*Cloud Foundry Buildpack Commands* |*Paketo Buildpacks Commands*
a| In CF Buildpacks, the Liberty for Java runtime includes a list of features that are available in Liberty. You can install features that aren't included in the runtime by running the `installUtility` command as a pre-runtime hook when the app is being pushed to IBM Cloud i.e. adding MicroProfile Config 3.0. 

* In the root directory of the app, create a `.profile.d` directory. Use the `.profile.d` feature to copy the manifest and feature jar to the user feature path and user bundle path. 

The script should look like the following:

[source, console]
----
#!/bin/sh
echo "Installing custom feature"
 
echo "Making directories...."
mkdir -p /home/vcap/app/wlp/usr/extension/lib/features
 
echo "Copying files..."
cp /home/vcap/app/.profile.d/.feature/cache.dummy_1.0.0.jar /home/vcap/app/wlp/usr/extension/lib/.
cp /home/vcap/app/.profile.d/.feature/cache.dummy_1.0.0.mf /home/vcap/app/wlp/usr/extension/lib/features/.
----

In this example the contents of the `.profile.d` directory is:

[source, console]
----
./instfeature.sh
./.feature
./.feature/cache.dummy_1.0.0.mf
./.feature/cache.dummy_1.0.0.jar
----

`Instfeature.sh` is the script containing the above content and the `.feature`` directory has the custom feature jar and manifest. 


a| **Using Custom Features:** 

First create the feature descriptor `features.toml` with the following content:
[source, toml]
----
[[features]]
  name = "dummyCache"
  uri = "file://features/cache.dummy_1.0.0.jar"
  version = "1.0.0"
  dependencies = ["distributedMap-1.0"]
----

Using the above feature description, the Liberty buildpack will look for the feature JAR in the volume mounted on `/features` at the path `features/cache.dummy_1.0.0.jar`. The buildpack also assumes that the feature manifest file will be at the path `features/cache.dummy_1.0.0.mf`. 
//***QUESTION*** here regarding the guide

After creating the feature descriptor, tar and gzip the `feature.toml` and `features` directory so that it has the contents similar to the following: 

[source, console]
----
$ tar tzf liberty-conf.tar.gz
./
./features/
./features.toml
./features/cache.dummy_1.0.0.mf
./features/cache.dummy_1.0.0.jar
----

Then, the custom features can be provided to the build by mounting the feature directory to `/features`:
[source, console]
pack build --path myapp --env BP_JAVA_APP_SERVER=liberty --volume path-to-features-directory:/features myapp

|=========

== Installing iFixes 

**Walkthrough:**

An iFix can be applied to the liberty runtime using a volume mount. 

There are the following requirements to install iFixes: 

* Only the archive versions of Liberty iFixes are supported 
* The iFixes are in a directory named `ifixes`

In this walkthrough, `22009-wlp-archive-ifph46816.jar` ifix was downloaded for the 22.0.0.9 release. The ifix is then placed into the `ifixes` directory. The directory should have the following structure:

[source, console]
ifixes/
22009-wlp-archive-ifph46816.jar

Specify the `--volume` parameter mapping your local `ifixes/` directory to `/ifixes` in the container

[source, console]
pack build --env BP_JAVA_APP_SERVER=liberty --volume path-to-ifixes:/ifixes --buildpack paketo-buildpacks/eclipse-openj9 --buildpack paketo-buildpacks/java your-app-here

The build output will show the iFix being applied: 

[source, console]
----
...
[builder]   Open Liberty (All Features) 22.0.9: Contributing to layer
[builder]     Downloading from https://repo1.maven.org/maven2/io/openliberty/openliberty-runtime/22.0.0.9/openliberty-runtime-22.0.0.9.zip
[builder]     Verifying checksum
[builder]     Expanding to /layers/paketo-buildpacks_liberty/open-liberty-runtime-full
[builder]     Installing features...
[builder]       Initializing ...
[builder]       Using 8 threads to download artifacts.
[builder]       Resolving remote features. This process might take several minutes to complete.
[builder]       The server does not require any additional features. No features were installed.
[builder]       Start product validation...
[builder]       Product validation completed successfully.
[builder]     Installing iFix 22009-wlp-archive-ifph46816.jar
[builder]       Applying fix to Liberty install directory at /layers/paketo-buildpacks_liberty/open-liberty-runtime-full now.
[builder]       	lib/com.ibm.ws.transport.http_1.0.68.cl220920220831-1859.jar
[builder]       	lib/com.ibm.ws.webcontainer.jakarta_1.1.68.cl220920220831-1859.jar
[builder]       	lib/com.ibm.ws.webcontainer_1.1.68.cl220920220831-1859.jar
[builder]       Fix has been applied successfully.
[builder]       Successfully extracted all product files.
...
----


[width="100%", cols="10, 10"]
[source, adoc]
|=========
|*Cloud Foundry Buildpack Commands* |*Paketo Buildpacks Commands*

a| **Applying iFix to the Liberty runtime**:

An iFix can be applied to an app using the `.profile.d` feature.

* Create the `.profile.d/.ifixes` directory in the root of the app that's being deployed to IBM Cloud
* Place the iFix `.jar` file in the `.profile.d/.ifixes/` directory
* Create `ifix.sh` file in the `.profile.d` directory with the following contents (update the <ifix filename> accordingly)
* If the iFix file can celany apply against the IBM Cloud version of Liberty, use the following script: 

[source, console]
#!/bin/sh
echo "Applying iFixes"
$HOME/.java/jre/bin/java -jar $HOME/.profile.d/.ifixes/<ifix filename>.jar --installLocation $HOME/.liberty/

* If the iFix file cannot cleanly apply, use the following script: 

[source, console]
#!/bin/sh
echo "Applying iFixes"
unzip $HOME/.profile.d/.ifixes/<ifix filename>.jar lib/*.jar -d $HOME/.liberty

For example, the contents of the `.profile.d` directory should look like the following: 

[source, console]
.profile.d/
.profile.d/.ifixes/16003-wlp-archive-IFPI68805.jar
.profile.d/ifix.sh

Once you deploy your application, you should see the following message that indicates which iFixes were applied:

[source, console]
CWWKF0015I: The server has the following interim fixes active in the runtime: PIXXXXX. For a full listing of installed fixes run: productInfo version --ifixes

a| **How to apply an iFix to the Liberty runtime**

An iFix can be applied to the liberty runtime using a volume mount. 
Specify the `--volume` parameter mapping your local `ifixes/` directory to `/ifixes` in the container

[source, console]
pack build myapp --env BP_JAVA_APP_SERVER=liberty --volume /path/to/ifixes:/ifixes

The build output will show the iFix being applied: 

|=========

== Using UBI images 

**Walkthrough:**

The Paketo buildpack can use Open Liberty runtime provided in the stack run image. This allows you to use the optimizations and configurations by IBM Cloud Container Registry (ICR) and more information can be found https://github.com/OpenLiberty/ci.docker/blob/main/docs/icr-images.md[here].

In the following steps, you will create three files: `bootstrap.sh`, `Dockerfile`, and `builder.toml`.

1) The first step, in a directory of your choosing, create a `bootstrap.sh` file with the following contents. This file will be in the same directory as your `Dockerfile`. The script is necessary to be able to grab the configuration and application created by the buildpacks. Confirm that the `bootstrap.sh` is executable before proceeding to the next step.

[source, shellscript]
----
#!/usr/bin/env bash

main() {
  readonly LIBERTY_USR_DIRS=(
    "/workspace/wlp/usr"
    "/workspace/usr"
    "/layers/paketo-buildpacks_liberty/base/wlp/usr"
  )

  for liberty_usr_dir in "${LIBERTY_USR_DIRS[@]}"; do
    if [[ -d "${liberty_usr_dir}" ]]; then
      local usr_dir="${liberty_usr_dir}"
      break
    fi
  done

  cp -rf "${usr_dir}/." "${BPI_LIBERTY_RUNTIME_ROOT}/usr/"

  # Call Liberty runtime's bootstrap script
  docker-server.sh "${@}"
}

main "${@}"
----

Second, create the Dockerfile and add the following to the file. In this walkthrough, we will be pulling the `open-liberty:kernel-slim-java11-openj9-ubi` version.

[source, shellscript]
----
# RUN IMAGE
FROM icr.io/appcafe/open-liberty:kernel-slim-java11-openj9-ubi as run

ENV CNB_USER_ID=1001
ENV CNB_GROUP_ID=0
ENV CNB_STACK_ID="io.buildpacks.stacks.liberty"
LABEL io.buildpacks.stack.id="io.buildpacks.stacks.liberty"

# Set environment variables used by the Open Liberty CNB.
ENV SERVICE_BINDING_ROOT=/platform/bindings
ENV BPI_LIBERTY_ROOT=/opt/ol
ENV BPI_LIBERTY_RUNTIME_ROOT=${BPI_LIBERTY_ROOT}/wlp
ENV WLP_USER_DIR=${BPI_LIBERTY_RUNTIME_ROOT}/usr
ENV PATH=${BPI_LIBERTY_ROOT}/helpers/runtime:${BPI_LIBERTY_RUNTIME_ROOT}/bin:${PATH}

# Set user and group (as declared in the base image)
USER ${CNB_USER_ID}

COPY --chown=${CNB_USER_ID}:${CNB_GROUP_ID} bootstrap.sh ${BPI_LIBERTY_ROOT}/helpers/runtime/

# This script will add the requested server configurations (optionally), apply any interim fixes (optionally) and populate caches to optimize runtime
RUN configure.sh

FROM registry.access.redhat.com/ubi8/ubi:8.5 as build

# BUILD IMAGE
ENV CNB_USER_ID=1001
ENV CNB_GROUP_ID=0
ENV CNB_STACK_ID="io.buildpacks.stacks.liberty"
LABEL io.buildpacks.stack.id="io.buildpacks.stacks.liberty"

# Provides hint to the Open Liberty buildpack which version of Liberty is being used at build time
ENV BPI_LIBERTY_RUNTIME_ROOT=/opt/ol/wlp
RUN mkdir -p ${BPI_LIBERTY_RUNTIME_ROOT}

RUN useradd --uid ${CNB_USER_ID} --gid ${CNB_GROUP_ID} -m -s /bin/bash cnb

RUN yum -y install git wget jq && wget https://github.com/sclevine/yj/releases/download/v5.0.0/yj-linux -O /usr/local/bin/yj && chmod +x /usr/local/bin/yj

# Set user and group (as declared in the base image)
USER ${CNB_USER_ID}
----

Third, after preparing the `Dockerfile` for the stack, use the following commands to build the run and build images that will be used: 

[source, console]
docker build -t <image-name>-run:latest --target run .
docker build -t <image-name>-build:latest --target build .

Replace `<image-name>` with the image name that you would like to use.

The `docker build -t <image-name>-run:latest --target run .` command will have the following output if successful: 

[source, console]
----
 => [internal] load build definition from Dockerfile                                                                                                                                    0.0s
 => => transferring dockerfile: 37B                                                                                                                                                     0.0s
 => [internal] load .dockerignore                                                                                                                                                       0.0s
 => => transferring context: 2B                                                                                                                                                         0.0s
 => [internal] load metadata for icr.io/appcafe/open-liberty:kernel-slim-java11-openj9-ubi                                                                                              0.3s
 => [internal] load build context                                                                                                                                                       0.0s
 => => transferring context: 514B                                                                                                                                                       0.0s
 => CACHED [run 1/3] FROM icr.io/appcafe/open-liberty:kernel-slim-java11-openj9-ubi@sha256:43b1b7a94fa6fc428767e6b39368907ca319979203a0b6ee0d7af983eff4402e                             0.0s
 => [run 2/3] COPY --chown=1001:0 bootstrap.sh /opt/ol/helpers/runtime/                                                                                                                 0.0s
 => [run 3/3] RUN configure.sh                                                                                                                                                          4.6s
 => exporting to image                                                                                                                                                                  0.1s
 => => exporting layers                                                                                                                                                                 0.1s
 => => writing image sha256:89212c1d996f6fe08f3d0410bc09ccca33d60315a50682db6a34da8420b718a8                                                                                            0.0s
 => => naming to docker.io/library/starter-image-run:latest                                                                                                                             0.0s
----

The `docker build -t <image-name>-build:latest --target build .` command will have the following output if successful:

[source, console]
----
 => [internal] load build definition from Dockerfile                                                                                                                                    0.0s
 => => transferring dockerfile: 37B                                                                                                                                                     0.0s
 => [internal] load .dockerignore                                                                                                                                                       0.0s
 => => transferring context: 2B                                                                                                                                                         0.0s
 => [internal] load metadata for registry.access.redhat.com/ubi8/ubi:8.5                                                                                                                0.8s
 => [build 1/4] FROM registry.access.redhat.com/ubi8/ubi:8.5@sha256:798025840cb82140df8d05775f7f55fff3b16a599bd5ca76b11594f7a9a595fa                                                    0.0s
 => CACHED [build 2/4] RUN mkdir -p /opt/ol/wlp                                                                                                                                         0.0s
 => CACHED [build 3/4] RUN useradd --uid 1001 --gid 0 -m -s /bin/bash cnb                                                                                                               0.0s
 => CACHED [build 4/4] RUN yum -y install git wget jq && wget https://github.com/sclevine/yj/releases/download/v5.0.0/yj-linux -O /usr/local/bin/yj && chmod +x /usr/local/bin/yj       0.0s
 => exporting to image                                                                                                                                                                  0.0s
 => => exporting layers                                                                                                                                                                 0.0s
 => => writing image sha256:c8325b72e4110a245c993930f75a89d3f525e66158358a4e79bcd6127b9d27c7                                                                                            0.0s
 => => naming to docker.io/library/starter-image-build:latest                                                                                                                           0.0s
----

Fourth, create a custom builder by creating a `builder.toml` file with the following contents: 

[source, toml]
----
[[buildpacks]]
  uri = "docker://gcr.io/paketo-buildpacks/ca-certificates"

[[buildpacks]]
  uri = "docker://gcr.io/paketo-buildpacks/eclipse-openj9"

[[buildpacks]]
  uri = "docker://gcr.io/paketo-buildpacks/syft"

[[buildpacks]]
  uri = "docker://gcr.io/paketo-buildpacks/leiningen"

[[buildpacks]]
  uri = "docker://gcr.io/paketo-buildpacks/gradle"

[[buildpacks]]
  uri = "docker://gcr.io/paketo-buildpacks/maven"

[[buildpacks]]
  uri = "docker://gcr.io/paketo-buildpacks/liberty"

[[buildpacks]]
  uri = "docker://gcr.io/paketo-buildpacks/procfile"

[[buildpacks]]
  uri = "docker://gcr.io/paketo-buildpacks/environment-variables"

[[buildpacks]]
  uri = "docker://gcr.io/paketo-buildpacks/image-labels"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/eclipse-openj9"
    optional = false

  [[order.group]]
    id = "paketo-buildpacks/syft"
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/gradle"
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/maven"
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/liberty"
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true

[stack]
  id = "io.buildpacks.stacks.liberty"
  run-image = "<image-name>-run:latest"
  build-image = "<image-name>-build:latest"
----

Replace the `stack.run-image` and `stack.build-image` values with your `image-name` value you used. Then the builder can be used by running the following command: 

[source, console]
pack -v builder create mybuilder:latest --config builder.toml

The above command will have the following output:

[source, console]
----
Pulling image starter-image-run:latest
Pulling image starter-image-build:latest
Creating builder mybuilder:latest from build-image starter-image-build:latest
...
Status: Image is up to date for gcr.io/paketo-buildpacks/image-labels:latest
Creating builder with the following buildpacks:
-> paketo-buildpacks/ca-certificates@3.4.0
-> paketo-buildpacks/eclipse-openj9@9.7.0
-> paketo-buildpacks/syft@1.21.0
-> paketo-buildpacks/leiningen@4.4.0
-> paketo-buildpacks/gradle@6.8.0
-> paketo-buildpacks/maven@6.11.0
-> paketo-buildpacks/liberty@2.4.0
-> paketo-buildpacks/procfile@5.4.0
-> paketo-buildpacks/environment-variables@4.3.0
-> paketo-buildpacks/image-labels@4.3.0
Adding buildpack paketo-buildpacks/image-labels@4.3.0 (diffID=sha256:6613db21bd509b876a76e2c3cca317f32141e2243d8e2a231f88517dcc88ffcf)
Adding buildpack paketo-buildpacks/ca-certificates@3.4.0 (diffID=sha256:0c16b901029079ec6f2f154f2bcf7b82c932bbfe8bd7665e9d753b0869491fb2)
Adding buildpack paketo-buildpacks/eclipse-openj9@9.7.0 (diffID=sha256:fbe1a86cae3b45034e26c29d46f60dcd289ad43f61ba98955514376c174de5ee)
Adding buildpack paketo-buildpacks/leiningen@4.4.0 (diffID=sha256:dca34fe44b9c62ddab049fa3638703ca40d12dc3a37f83cc892d5c3a6b3b9075)
Adding buildpack paketo-buildpacks/liberty@2.4.0 (diffID=sha256:9c8a0114133fc3aa2765216509a020983d5d16cd3bfaa5d958818344b995c083)
Adding buildpack paketo-buildpacks/procfile@5.4.0 (diffID=sha256:8c184880fd75919ea528e3f506e93f99022eecbbcb5a797c5cf134806bb13761)
Adding buildpack paketo-buildpacks/environment-variables@4.3.0 (diffID=sha256:0952cc879389c15fa9f4dd50fe9365d672a0ec4e751438899eda65c782fa1b4c)
Adding buildpack paketo-buildpacks/syft@1.21.0 (diffID=sha256:e9482447bd072ccbd758e5bf6517123f724e3cd3f1ed85e76bdfc55c2e54e947)
Adding buildpack paketo-buildpacks/gradle@6.8.0 (diffID=sha256:a707ff8bbd5a93e09a6b9973a55e096c48a9f5768865b0db25a6a36046355df6)
Adding buildpack paketo-buildpacks/maven@6.11.0 (diffID=sha256:53d7320eb399555d2eb990958b8624ea6ff2a4beccc3b9aa8041294dd9db1b9d)
Successfully created builder image mybuilder:latest
----

Fifth, with the stack images and custom builder created, you can deploy a Liberty application by using the following `pack build` command: 

[source, console]
pack build myapp --builder mybuilder:latest --env BP_LIBERTY_INSTALL_TYPE="none"

If the above `pack build` command is successful, it will have the following output. Look for `boostrap.sh server run DefaultServer (direct)` and `Successfully built image` in the output.

[source, console]
----
0.14.1: Pulling from buildpacksio/lifecycle
36698cfa5275: Pull complete
4f80531f7622: Pull complete
Digest: sha256:56019ba74831e3444f33ee8c0201f18cc300213bac353b8b6a79c7a1669b7a49
Status: Downloaded newer image for buildpacksio/lifecycle:0.14.1
===> ANALYZING
[analyzer] Restoring data for SBOM from previous image
===> DETECTING
[detector] 5 of 9 buildpacks participating
[detector] paketo-buildpacks/ca-certificates 3.4.0
[detector] paketo-buildpacks/eclipse-openj9  9.7.0
[detector] paketo-buildpacks/syft            1.21.0
[detector] paketo-buildpacks/maven           6.11.0
[detector] paketo-buildpacks/liberty         2.4.0
...
[builder] Paketo Buildpack for Liberty 2.4.0
[builder]   https://github.com/paketo-buildpacks/liberty
[builder]   Build Configuration:
[builder]     $BP_JAVA_APP_SERVER             the application server to use
[builder]     $BP_LIBERTY_FEATURES            A space separated list of liberty features to install.
[builder]     $BP_LIBERTY_INSTALL_TYPE  none  Install type of Liberty
[builder]     $BP_LIBERTY_PROFILE             The Liberty profile to install
[builder]     $BP_LIBERTY_SERVER_NAME         Name of the server to use
[builder]     $BP_LIBERTY_VERSION       *     Which version of the Liberty runtime to install
[builder]   Launch Configuration:
[builder]     $BPL_LIBERTY_LOG_LEVEL          Sets the logging level
[builder]     $BP_LIBERTY_CONTEXT_ROOT        Context root to use for app
[builder]     $BP_LIBERTY_SERVER_NAME         Name of the server to use
[builder]   Launch Helper: Reusing cached layer
[builder]   Open Liberty Config: Reusing cached layer
[builder]   Process types:
[builder]     open-liberty-stack: bootstrap.sh server run defaultServer (direct)
===> EXPORTING
[exporter] Reusing layer 'paketo-buildpacks/ca-certificates:helper'
[exporter] Reusing layer 'paketo-buildpacks/eclipse-openj9:helper'
[exporter] Reusing layer 'paketo-buildpacks/eclipse-openj9:java-security-properties'
[exporter] Reusing layer 'paketo-buildpacks/eclipse-openj9:jre'
[exporter] Reusing layer 'paketo-buildpacks/liberty:base'
[exporter] Reusing layer 'paketo-buildpacks/liberty:helper'
[exporter] Reusing layer 'launch.sbom'
[exporter] Reusing 1/1 app layer(s)
[exporter] Reusing layer 'launcher'
[exporter] Reusing layer 'config'
[exporter] Reusing layer 'process-types'
[exporter] Adding label 'io.buildpacks.lifecycle.metadata'
[exporter] Adding label 'io.buildpacks.build.metadata'
[exporter] Adding label 'io.buildpacks.project.metadata'
[exporter] Setting default process type 'open-liberty-stack'
[exporter] Saving myapp...
[exporter] *** Images (1345c46d6bb6):
[exporter]       myapp
[exporter] Reusing cache layer 'paketo-buildpacks/eclipse-openj9:jdk'
[exporter] Reusing cache layer 'paketo-buildpacks/syft:syft'
[exporter] Reusing cache layer 'paketo-buildpacks/maven:application'
[exporter] Reusing cache layer 'paketo-buildpacks/maven:cache'
[exporter] Reusing cache layer 'paketo-buildpacks/maven:maven'
[exporter] Reusing cache layer 'cache.sbom'
Successfully built image myapp
----

[width="100%", cols="10, 10"]
[source, adoc]
|=========
|*Cloud Foundry Buildpack Commands* |*Paketo Buildpacks Commands*
a| Push a Docker Image from a Registry:

Cloud Foundry supports pushign apps from container registries such as Docker Hub, Google Container Registry (GCR), and Amazon Elastic Container Registry (ECR).

How you run `cf push` with apps stored in container

[source, console]
cf push APP-NAME --docker-image REPO/IMAGE:TAG

More reference information on pushing an app in CF using a docker image can be found here: https://docs.cloudfoundry.org/devguide/deploy-apps/push-docker.html[Deploying an App with Docker]

a| Using a Liberty Runtime Provided in the Stack Run Image

**Building the stack images:**

When creating the `Dockerfile`, you can use different images by specifying the UBI images in the first line of `Dockerfile` found here: https://github.com/OpenLiberty/ci.docker/blob/main/docs/icr-images.md[IBM Cloud Container Registry documentation].

After preparing the `Dockerfile` for the stack, use the following commands to build the run and build images that will be used: 

[source, console]
docker build -t <image-name>-run:latest --target run .
docker build -t <image-name>-build:latest --target build .

Replace `<image-name` with whatever image name you would like to use.

**Deploying a Liberty application:**

Use the following command with custom stack images and builder specified:

[source, console]
$ pack build myapp --builder mybuilder:latest --env BP_LIBERTY_INSTALL_TYPE="none"

**Other information:**

Further information regarding "Installing Open Liberty or Websphere Liberty iFixes" and "Installing Open Liberty or Websphere Liberty features" can be found in the following https://github.com/kevin-ortega/liberty/blob/updateStackDoc/docs/using-liberty-stack.md[documentation update].

|=========








// ------------ END ------------