// ----------- BEGIN -----------
// Copyright (c) 2019, 2022 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//

// :projectid: paketo-buildpacks-intro
:page-layout: guide-multipane
// :page-duration: 15 minutes
// :page-releasedate: TBD
:page-description: Learn how to migrate an application using Cloud Foundry buildpacks to Paketo buildpacks. 
// :page-tags: 
// :page-permalink: /guides/{projectid}
// :page-related-guides: ['docker', 'kubernetes-intro']
// :common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/prod
// :page-guide-category: 
:page-essential: true
// :page-essential-order: 3
:source-highlighter: prettify
// :page-seo-title: 
// :page-seo-description: 
// :common-includes: ../guides-common/
// :imagesdir: /img/guide/{projectid}

// :guide-author: Open Liberty
= Migrating an application using Cloud Foundry Buildpacks to Paketo Buildpacks

You will explore how to migrate an application using Cloud Foundry liberty-for-java buildpack to using Paketo buildpacks.

// =================================================================================================
//  What you'll learn
// =================================================================================================

== What you'll learn

Learn how to migrate an application using Cloud Foundry liberty-for-java buildpack to using Paketo buildpacks. You will learn how to migrate and use advanced features of the Paketo buildpack. 

The migration includes learning how to use the following features: 

* Simple migration
* Providing server.xml at build time 
* Using different profiles (full, jakarta9, webProfile9, webProfile8, javaee8, microProfile4, microProfile5, kernel)
* Building from a Liberty Server 
* Building from a Packaged Server.
* Installing custom features 
* Installing iFixes
* Using UBI images 

== Additional prerequisites

* Your application source 
* https://hub.docker.com/search?type=edition&offering=community&q=[Docker]
* The https://buildpacks.io/docs/tools/pack/[pack CLI]
 
== Simple migration 
//start with getting started blog post
//simple migration - push using a war file
//paketo.io and buildpacks.io website as references

[width="100%", cols="10, 10"]
[source, adoc]
|=========
|*Cloud Foundry Buildpack Commands* |*Paketo Buildpacks Commands* 
// a| Navigate to source code repository (will use Getting started app for example)
// // delete cell
// [source, console]
// git clone https://github.com/IBM-Cloud/get-started-java


  
// a| Navigate to source code repository (will use Getting started app for example)
// //delete cell
// [source, console]
// git clone https://github.com/openliberty/guide-getting-started.git
// cd guide-getting-started/finish

// a| Run app locally using command line 
// [source, console]
// cd get-started-java
// mvn clean install
// mvn install liberty:run-server

// a| Create an OCI image and run application locally
// [source, console]
// pack config default-builder gcr.io/paketo-buildpacks/builder:base

// [source, console]
// pack build --env BP_JAVA_APP_SERVER=liberty --env BP_LIBERTY_PROFILE=jakartaee9 \
//   --buildpack paketo-buildpacks/eclipse-openj9 --buildpack paketo-buildpacks/java myapp

// [source, console]
// docker run --rm -p 9080:9080 myapp


a| Push app using cloud foundry
[source, console]
cf push -p myApp.war

a| Create an OCI image and run application locally
//Say something about the pack config command what it does

The pack config command sets the default builder using the pack CLI.
[source, console]
pack config default-builder gcr.io/paketo-buildpacks/builder:base

The pack build command uses Cloud Native Buildpacks to create an app image from the source code. More info found here: https://buildpacks.io/docs/tools/pack/cli/pack_build/[pack build] 
[source, console]
pack build --env BP_JAVA_APP_SERVER=liberty 
// --env BP_LIBERTY_PROFILE=jakartaee9 \
//   --buildpack paketo-buildpacks/eclipse-openj9 --buildpack paketo-buildpacks/java myapp

[source, console]
docker run --rm -p 9080:9080 myapp
// a| Build app from an on-prem Open Liberty installation
// [source, console]
// bin/server package defaultServer --include=usr

// [source, console]
// pack build --path <packaged-server-zip-path> \
//  --buildpack paketo-buildpacks/eclipse-openj9 \
//  --buildpack paketo-buildpacks/java myapp

|=========

== Providing server.xml at build time

[width="100%", cols="10, 10"]
[source, adoc]
|=========
|*Cloud Foundry Buildpack Commands* |*Paketo Buildpacks Commands* 

a| Custom Liberty server configuration with your app

Install the Liberty profile to your workstation. Instructions found here: https://cloud.ibm.com/docs/cloud-foundry-public?topic=cloud-foundry-public-options_for_pushing#server_directory[Server directory]

Run the command:
[source, console]
cf push <yourappname> -p wlp/usr/servers/defaultServer

a| Using server.xml at build time:author:

Run the following commands: 

Navigate to getting-started-java directory or any sample app
[source, console]
pack config default-builder gcr.io/paketo-buildpacks/builder:base

Build the application on Liberty:
[source, console]
pack build --env BP_JAVA_APP_SERVER=liberty

When providing server configuration files like server.xml, these files can only be included in the build by telling the Maven or Gradle buildpacks to provide them. The following environment variables need to be set in your pack build command.

Server Config with Maven applications
[source, console]
--env BP_MAVEN_BUILT_ARTIFACT="target/*.[ejw]ar src/main/liberty/config/*"

Server Config with Gradle applications
[source, console]
--env BP_GRADLE_BUILT_ARTIFACT="build/libs/*.[ejw]ar src/main/liberty/config/*"

//Add a generic location for server config file. Using bindings 

Check if the server.xml file is in the directory: 
[source, console]
docker exec -it $(docker ps -q) /bin/bash

a| Binding service 

[source, console]
cf bind-service

a| Using bindings - providing server config at build and runtime

Providing server config at build-time and runtime used for secret configuration. Bindings provide credentials and location needed to connect to external services. First create the bindings/liberty folder and add the type file with liberty. Add any config you want to provide at runtime in the directory and the nmount the folder during docker run with --volume $(pwd)/bindings:/platform/bindings

[source, console]
docker run --env SERVICE_BINDING_ROOT=/bindings --volume <absolute-path-to-binding>:/bindings/<binding-name> <image-name>

|=========


=== Using different profiles 
//Offering different profiles javaee6, javaee7, javaee8
* Full, jakarta9, webProfile9, webProfile8, javaee8, microProfile4, microProfile5, kernel

[width="100%", cols="10, 10"]
[source, adoc]
|=========
|*Cloud Foundry Buildpack Commands* |*Paketo Buildpacks Commands* 

a| The CF liberty-for-java buildpack allows for the following profiles to be used: javaee6, javaee7, javaee8. These profiles can be installed using the following cf commmand and environment variable: 

[source, console]
cf set-env myapp JBP_CONFIG_LIBERTY "app_archive: {features: [javaee8]}”

a| The different profiles can be installed by using the _pack build --env_ command and including the BP_LIBERTY_PROFILE environment variable. For example, to include jakartaee9 profile, the following command will be run: 

[source, console]
pack build --env BP_JAVA_APP_SERVER=liberty --env BP_LIBERTY_PROFILE=jakartaee9



|=========

=== Building from a Liberty server 

[width="100%", cols="10, 10"]
[source, adoc]
|=========
|*Cloud Foundry Buildpack Commands* |*Paketo Buildpacks Commands* 

a| In the CF buildpacks, providing a custom Liberty server configuration requires editing the `server.xml` file. Create a `apps` directory within the `defaultServer` directory i.e. `defaultServer/apps`. In that directory a `server.xml` file can be created and placed in `defaultServer` directory. 

Once the server directory is ready the following command can be used to deploy to IBM Cloud

[source, console]
cf push <yourappname> -p defaultServer

a| The buildpack can build from a Liberty server installation directory or from a packaged server. 

To build from a Liberty server installation, change your working directory to the installation root containing the `wlp` directory and run the following command: 

[source, console]
pack build --env BP_JAVA_APP_SERVER=liberty myapp

|=========

=== Building from a Packaged Server
[width="100%", cols="10, 10"]
[source, adoc]
|=========
|*Cloud Foundry Buildpack Commands* |*Paketo Buildpacks Commands*
a| In CF buildpacks you can also push a packaged server to IBM Cloud by creating the file using Liberty's server package command. To package a Liberty server, use the `./bin/server package` command from the installed app directory. Specify the server name and include the `--include=usr` option. The CF command to package a Liberty server is the following: 

[source, console]
wlp/bin/server package server_name_here --include=usr

This command generates a `serverName.zip` file in the server's directory and the following commmand pushes the zip file to IBM Cloud:

[source, console]
cf push <yourappname> -p wlp/usr/servers/defaultServer/defaultServer.zip

a| Building from a Packaged Server: Use the `server package` command of the Liberty runtime to create a packaged server. Run the following command from Liberty installation's `wlp` directory:app-name:

[source, console]
bin/server package defaultServer --include=usr

Then the packaged server can be supplied to the build by using the `--path` argument: 
[source, console]
pack build --env BP_JAVA_APP_SERVER=liberty --path <packaged-server-zip-path> myapp

|=========

=== Installing custom features
[width="100%", cols="10, 10"]
[source, adoc]
|=========
|*Cloud Foundry Buildpack Commands* |*Paketo Buildpacks Commands*
a| In CF Buildpacks, the Liberty for Java runtime includes a list of features that are available in Liberty. You can install features that aren't included in the runtime by running the `installUtility` command as a pre-runtime hook when the app is being pushed to IBM Cloud i.e. adding MicroProfile Config 3.0. 

In the root directory of the app, create a `.profile.d` directory. In the `.profile.d` directory, create a script file that runs the `installUtility` command. 

[source, console]
----
#!/bin/sh
echo "Installing audit-1.0"
export PATH=$PATH:$HOME/app/.java/jre/bin

$HOME/app/.liberty/bin/installUtility install audit-1.0 --acceptLicense
----
a| **Using Custom Features:** Custom features can can either be configured on the server or using a volume mount to `/features` that contains the feature JARs and manifests along with a feature descriptor.

**Feature Manifest:** The feature manifest is a `features.toml` file containing a list of `features` that would be installed on the server.

A feature has the following properties:
[disc]
* `name`: Name of the feature to enable. Use symbolic name of the feature that you would use when enabling the feature in the `server.xml`
* `uri`: URI of where to find the fetaure. The `file` scheme is the only supported scheme at the moment.
* `version`: Version of the feature
* `dependencies`: List of features that the custom feature depends on

**Example Feature Manifest**: This example shows how to configure a feature called `dummyCache` that has a dependency `distributedMap-1.0` feature. Any additional features added will use the same format as the example below.

First create the feature descriptor `features.toml` with the following content:
[source, toml]
----
[[features]]
  name = "dummyCache"
  uri = "file://features/cache.dummy_1.0.0.jar"
  version = "1.0.0"
  dependencies = ["distributedMap-1.0"]
----

Using the above feature description, the Liberty buildpack will look for the feature JAR in the volume mounted on `/features` at the path `features/cache.dummy_1.0.0.jar`. The buildpack also assumes that the feature manifest file will be at the path `features/cache.dummy_1.0.0.mf`. 
//***QUESTION*** here regarding the guide

After creating the feature descriptor, tar and gzip the `feature.toml` and `features` directory so that it has the contents similar to the following: 

[source, console]
----
$ tar tzf liberty-conf.tar.gz
./
./features/
./features.toml
./features/cache.dummy_1.0.0.mf
./features/cache.dummy_1.0.0.jar
----

Then, the custom features can be provided to the build by mounting the feature directory to `/features`:
[source, console]
pack build --path myapp --env BP_JAVA_APP_SERVER=liberty --volume /Users/userNameHere/Development/paketo-buildpacks/liberty-e2e.bak/data/conf/features:/features myapp

|=========


=== Using UBI images 

=== Installing iFixes 







// ------------ END ------------